### ISSUE TITLE
search-courses.json not found

### ISSUE THREAD

**Issue by farsidd** [muhamed-didovic/vsdown#5]
I am getting this error while running the command even vsdown command throwing this error.
Error: Cannot find module 'C:\Users\Public\vueschool_vid_scrapper\json\search-courses.json'
![error](https://github.com/muhamed-didovic/vsdown/assets/45181106/038b74c9-38c9-4662-877d-8fe270d45449)

**Comment by muhamed-didovic** [comment]
verify if there is json folder and search-courses.json file inside of it?

**Comment by farsidd** [comment]
i have simply installed yt-dlp package and then added it to environment variable afther that install vsdown package globally as you said in the docs and then simply use that command
"vsdown https://vueschool.io/courses/laravel-backends-for-vue-js-3 -e farhanfsd.pk@gmail.com -p testPass -d Downloads"
after running this command i got error i mentioned above.
I don't know where to look json folder or search-courses.json as i have installed the package globally.

**Comment by muhamed-didovic** [comment]
hey @farsidd, shoot me an email

**Comment by farsidd** [comment]
somehow i solved the issue by downloading cloning the repositery and copy the json folder to vsdown folder where i installed this library globally. But now there's another issue now :) it downloaded everything like html,markdown, pdf & screenshots but not video which i needed the most.
i run this command
"vsdown https://vueschool.io/courses/laravel-backends-for-vue-js-3 -e farhanfsd.pk@gmail.com -p testPass -d Downloads"

**Comment by gtoborges** [comment]
Hi, I had the same problem. I think it is trying to find two json files (download-courses and search-courses) when you are executing with npx from the directory you're in/json/*.json.

For example, I was executing npx vsdown on my dir /home/user/videos/vueschool... and it crashed just as reported initially searching for the jsons in /home/user/videos/vueschool/json/*.json

It worked when I downloaded and executed with node. Then I saw the jsons and created the json directory /home/user/videos/vueschool/json/ and copied the files there. After doing so, I executed npx vsdown and it worked as intended.

But I didn't get it how it was supposed to work, and it stuck in the end and just generated these files:
![image](https://github.com/muhamed-didovic/vsdown/assets/22681828/0e3f510d-9ce3-4dbb-a3bf-ccc40663129d)

**Comment by farsidd** [comment]
> Hi, I had the same problem. I think it is trying to find two json files (download-courses and search-courses) when you are executing with npx from the directory you're in/json/*.json.
> 
> For example, I was executing npx vsdown on my dir /home/user/videos/vueschool... and it crashed just as reported initially searching for the jsons in /home/user/videos/vueschool/json/*.json
> 
> It worked when I downloaded and executed with node. Then I saw the jsons and created the json directory /home/user/videos/vueschool/json/ and copied the files there. After doing so, I executed npx vsdown and it worked as intended.
> 
> But I didn't get it how it was supposed to work, and it stuck in the end and just generated these files: ![image](https://user-images.githubusercontent.com/22681828/280537526-0e3f510d-9ce3-4dbb-a3bf-ccc40663129d.png)

brother it will not work for free weekend access. you can see you can not download even login your account via web and you will see the download button is not available even thoough we have premium access for 2 days. even idm not picking up the video for download. i have downloaded video through chrome extension named "Video DownloadHelper" but the video is also not playing properly in VLC, Windows Media Player or Windows Media Player Classic.
they have put some heavy restrictions or security.

but i think this library will work perfectly for premium account other than free weekend access.

**Comment by muhamed-didovic** [comment]
hey guys, I pushed new version, also json folder is published so those files should be available, so upgrade to new version and let's how it goes

**Comment by gtoborges** [comment]
Worked perfectly! Thank you so much!

**Comment by farsidd** [comment]
perfectly working. Thanks
