### ISSUE TITLE
Unavailable dependency

### ISSUE THREAD

**Issue by chefkold** [muhamed-didovic/vsdown#6]
yt-dlp dependencies are blocked? (451).

**Comment by muhamed-didovic** [comment]
@chefkold I don't have issues with yt-dlp?

**Comment by chefkold** [comment]
It seems like the installation of the ytdl-run dependency might be blocked for some countries...
Could you add the commands to the readme to run the application locally instead of installing vsdown from NPM?

**Comment by muhamed-didovic** [comment]
clone it and run it as: node lib/cli.js

**Comment by chefkold** [comment]
well, I still get a npm ERR! GotError [HTTPError]: Response code 451 (Unavailable For Legal Reasons) when npm installing locally. Anyway, it's probably a skill issue on my side.

**Comment by muhamed-didovic** [comment]
is yt-dlp up to date?

**Comment by chefkold** [comment]
Yeah, but the problem seems to be that that ytdl-run is origin blocked (blocked by EU maybe?) when installing from NPM. So this has nothing to do yet with yt-dlp local.

**Comment by amdest** [comment]
@chefkold — had this issue too.
Got it resolved by simply removing dependency for ytdl-run before `npm install` locally. At this moment yt-dlp should already be installed.

**Comment by chefkold** [comment]
Yeah, I tried that too and the tool seems to be functioning like it should, issue can be closed.
