### ISSUE TITLE
facing this issue when trying to download all at once

### ISSUE THREAD

**Issue by JaberWiki** [muhamed-didovic/vsdown#7]
![image](https://github.com/muhamed-didovic/vsdown/assets/55241455/bb704274-3d52-4c8d-bc3f-3a0faebd821e)

**Comment by muhamed-didovic** [comment]
hm, I see that for the first time, what about single course

**Comment by JaberWiki** [comment]
after updating *yt-dlp* the error has gone but now the download is puased maybe server is too much slow for now.
![image](https://github.com/muhamed-didovic/vsdown/assets/55241455/45d52a86-dc63-4bca-85b9-944c7f1eeff1)

**Comment by amdest** [comment]
@JaberWiki — start vsdown with logger debug enabled. It'll help to narrow the source of error.

**Comment by JaberWiki** [comment]
@amdest @muhamed-didovic  are you facing slow download issue?

**Comment by amdest** [comment]
> are you facing slow download issue?

@JaberWiki — no.

**Comment by JaberWiki** [comment]
@muhamed-didovic  if I don't want to download md files for all courses what to do?

**Comment by amdest** [comment]
@JaberWiki just pass a `--markdown no` argument to CLI

**Comment by JaberWiki** [comment]
@amdest  @muhamed-didovic  I want to also skip html folder.

**Comment by muhamed-didovic** [comment]
@JaberWiki use: -l no

**Comment by JaberWiki** [comment]
> @JaberWiki use: -l no

Thank you bro.
