### ISSUE TITLE
When using *npm i -g vsdown* getting this error

### ISSUE THREAD

**Issue by JaberWiki** [muhamed-didovic/vsdown#8]
![image](https://github.com/muhamed-didovic/vsdown/assets/55241455/80d35625-a256-4337-985a-ee759314a1ee)
@muhamed-didovic

**Comment by muhamed-didovic** [comment]
@JaberWiki, check this: https://github.com/muhamed-didovic/vsdown/issues/6

**Comment by JaberWiki** [comment]
if i can't use *npm i -g vsdown* then why you mentioned it in readme!

**Comment by muhamed-didovic** [comment]
you don't need to use this too at all

**Comment by JaberWiki** [comment]
Please organise the readme and add all flags and steps clearly
